bookmarker.vbs "WillowsPortal" "http://WillowsPortal.trabondev.com"
bookmarker.vbs "Aberdeen Heights Portal" "http://aberdeenheightsportal.trabondev.com"
bookmarker.vbs "Client Portal POC" "http://clientportalpoc.trabondev.com"
bookmarker.vbs "Euston Dev Portal" "http://eustonportal.trabondev.com"
bookmarker.vbs "ArtsKC Portal - Staging" "http://artskc.trabonstage.com"
bookmarker.vbs "Start KC" "http://StartKC.trabondev.com"
bookmarker.vbs "Parelli Portal" "http://parelli.trabontest.com"
bookmarker.vbs "Barrington Portal" "http://barrington.trabondev.com"
bookmarker.vbs "FF - track.familyfeatures.com" "http://track.familyfeatures.com"
bookmarker.vbs "We Plan Well Dev Portal" "http://weplanwell.trabondev.com"
bookmarker.vbs "Margaritas Portal - Dev" "http://margaritasportal.trabondev.com"
bookmarker.vbs "FVT POrtal 2010" "http://fvtportal.trabondev.com"
bookmarker.vbs "Fairfax Portal" "http://fairfaxportal.trabondev.com"
bookmarker.vbs "SedgwickPortal" "http://sedgwickportal.trabondev.com"
bookmarker.vbs "TheNewAdmiralPortal" "http://newadmiralportal.trabondev.com"
bookmarker.vbs "FF - www.familyfeatures.com" "http://familyfeatures.com"
bookmarker.vbs "Mayflower" "http://mayflower.trabondev.com"
bookmarker.vbs "PSI Portal" "http://psiportal.trabondev.com"
bookmarker.vbs "FF - foodeditor redirects " "http://www.foodeditor.com"
bookmarker.vbs "FF MRC" "http://ffmrc.trabondev.com"
bookmarker.vbs "FF-TS-Culinary.Net" "http://www.culinary.net"
bookmarker.vbs "Harris Construction Portal" "http://harrisportal.trabondev.com"
bookmarker.vbs "BurnsMcD Spacing" "http://burnsmcd-spacing.trabondev.com"
bookmarker.vbs "Magnum ENP Portal" "http://magnumenp.trabondev.com"
bookmarker.vbs "Insight Institute Online" "http://iio.trabontest.com:443"
bookmarker.vbs "Win Win KC" "http://winwinkc.trabondev.com"
bookmarker.vbs "ReliancePortal" "http://relianceportal.trabondev.com"
bookmarker.vbs "Pawsonality Portal" "http://pawsonality.trabonstage.com"
bookmarker.vbs "Plymouth09Portal" "http://Plymouth09Portal.trabondev.com"
bookmarker.vbs "FF - lifestyle.familyfeatures.com" "http://lifestyle.familyfeatures.com"
bookmarker.vbs "WePlanWell Internal Test Site" "http://weplanwell.trabontest.com"
bookmarker.vbs "FF-TS - Feeds2.familyfeatures.com" "http://feed2.familyfeatures.com"
bookmarker.vbs "Boise Portal" "http://boiseportal.trabondev.com"
bookmarker.vbs "MGC Enrollment" "http://enrollmgc.trabondev.com"
bookmarker.vbs "FF-TS - Marketers.FamilyFeatures.com" "http://marketers.familyfeatures.com"
bookmarker.vbs "Ship Rate Web Service" "http://shiprate.trabondev.com"
bookmarker.vbs "LewerWorks" "http://lewerworks.trabondev.com"
